### 予想される出力

5

### 実際の実行結果

5

### 上記の結果になった理由

catch節内にあるbreak文で、catch節から処理が外に移る(for文の外に移動する)が、
その前にfinally節内の処理の実行が割り込む。
finally節内に`continue`があるため、for文の先頭に処理が移る。
そのため、前述した`break`は実行されず、for文は5回ループが完了するまで回り続ける。
